### ISSUE TITLE
Problem with ./node_modules/tsx-control-statements/components.ts

### ISSUE THREAD

**Issue by HugoFortunato** [vkbansal/tsx-control-statements#19]
## Problem

Basically I get this message when implementing some lib component, for example For .

![image](https://user-images.githubusercontent.com/67443788/172712047-4a2b5f0e-b214-47b4-9084-d504aa2effa3.png)

I'm using nextjs.

I used this for installation in tsx:

`yarn add tsx-control-statements` (https://www.npmjs.com/package/tsx-control-statements)

`yarn add --save-dev babel-plugin-jsx-control-statements`

babel file:

```
{
  "presets": ["next/babel", "@babel/preset-typescript"],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "ssr": true,
        "displayName": true
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": [
        [
          "babel-plugin-styled-components",
          {
            "ssr": false,
            "displayName": false
          }
        ],
        ["jsx-control-statements"],
        ["transform-react-inline-elements"]
      ]
    }
  }
}
```

Can you help me? 

My typescript version now is: 4.4.0 and I use this repo for test: https://github.com/KonstantinSimeonov/tsx-control-statements

**Comment by vkbansal** [comment]
The package your are using is https://www.npmjs.com/package/tsx-control-statements and it resides at https://github.com/KonstantinSimeonov/tsx-control-statements.

This package is  `@vkbansal/tsx-control-statements` and my package is not meant to be used with babel.

Even the other package will not work with babel. You must use [jsx-control-statments](https://www.npmjs.com/package/babel-plugin-jsx-control-statements)
